# Generated by Django 6.0.2 on 2026-02-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('logo', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('founded', models.IntegerField(blank=True, null=True)),
                ('total_funding', models.CharField(blank=True, max_length=50)),
                ('last_signal', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
